language: node_js
node_js:
  - "0.12"
after_success:
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ];
       then surge ./src/ example-travisci-pullrequests.surge.sh;
       else surge ./src/ ${TRAVIS_PULL_REQUEST}.example-travisci-pullrequests.surge.sh;
    fi'
